import { Tool } from "./types";

export const tools: Array<Tool> = [
	{
		id: "negotiate",
		title: "Negotiate for maximum impact",
		label: "Negotiate",
		icon: "/icons/blocks.svg",
		theme: {
			background: "#FEEFE6",
		},
		items: [
			{
				text: "Assumptions Menu",
				category: "Adopt empowering mindsets",
				useCase: "Adopt a productive mindset and approach",
				slug: "/tools/negotiate/assumptions-menu",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Negotiation Strategies",
				category: "Adopt empowering mindsets",
				useCase: "Adopt a productive mindset and approach",
				slug: "/tools/negotiate/negotiation-strategies",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Negotiation Tendencies",
				category: "Adopt empowering mindsets",
				useCase: "Adopt a productive mindset and approach",
				slug: "/tools/negotiate/negotiation-tendencies",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Parties Map",
				category: "Adopt empowering mindsets",
				useCase: "Focus on inclusive positive impact",
				slug: "/tools/negotiate/parties-map",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Impact Focus",
				category: "Adopt empowering mindsets",
				useCase: "Focus on inclusive positive impact",
				slug: "/tools/negotiate/impact-focus",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Cheatsheet",
				category: "Adopt empowering mindsets",
				useCase: "Keep learning from all experiences",
				slug: "/tools/negotiate/cheatsheet",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Negotiation Canvas",
				category: "Prepare with the Negotiation Canvas",
				useCase: "Prepare systematically for any negotiation",
				slug: "/tools/negotiate/negotiation-canvas",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Role Play",
				category: "Apply, impact, and learn",
				useCase: "Practice deliberately for best outcomes",
				slug: "/tools/negotiate/role-play",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Negotiation Debrief",
				category: "Apply, impact, and learn",
				useCase: "Keep learning from all experiences",
				slug: "/tools/negotiate/negotiation-debrief",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "NegoJournal",
				category: "Apply, impact, and learn",
				useCase: "Keep learning from all experiences",
				slug: "/tools/negotiate/negojournal",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Capstone Exam",
				category: "Apply, impact, and learn",
				useCase: "Practice deliberately for best outcomes",
				slug: "/tools/negotiate/capstone-exam",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Pay It Forward",
				category: "Apply, impact, and learn",
				useCase: "Spread these ideas",
				slug: "/tools/negotiate/pay-it-forward",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Win-Win Organizations",
				category: "Apply, impact, and learn",
				useCase: "Spread these ideas",
				slug: "/tools/negotiate/win-win-organizations",
				icon: "/vectors/tools/tool.png",
			},
		],
	},
	{
		id: "connect",
		title: "Connect through a solid bridge",
		label: "Connect",
		icon: "/icons/arch.svg",
		theme: {
			background: "#EEFAFF",
		},
		items: [
			{
				text: "Opening Plan",
				category: "Improve the working relationship",
				useCase: "Connect well with others from the start",
				slug: "/tools/connect/opening-plan",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Interdependence",
				category: "Improve the working relationship",
				useCase: "Build trust and a solid relationship",
				slug: "/tools/connect/interdependence",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Trust Equation",
				category: "Improve the working relationship",
				useCase: "Build trust and a solid relationship",
				slug: "/tools/connect/trust-equation",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Unconditionally Constructive Behaviors",
				category: "Improve the working relationship",
				useCase: "Build trust and a solid relationship",
				slug: "/tools/connect/unconditionally-constructive-behaviors",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Oel Ngati Kameie",
				category: "Improve the working relationship",
				useCase: "Connect well with others from the start",
				slug: "/tools/connect/oel-ngati-kameie",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Go to the Balcony",
				category: "Improve the working relationship",
				useCase:
					"Manage emotions and difficult interactions positively",
				slug: "/tools/connect/go-to-the-balcony",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Powerful Questions",
				category: "Establish effective and efficient communication",
				useCase: "Ask good questions for best learning",
				slug: "/tools/connect/powerful-questions",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Meta Model",
				category: "Establish effective and efficient communication",
				useCase: "Ask good questions for best learning",
				slug: "/tools/connect/meta-model",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Translator",
				category: "Establish effective and efficient communication",
				useCase: "Communicate effectively and promote understanding",
				slug: "/tools/connect/translator",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Ladder of Inference",
				category: "Establish effective and efficient communication",
				useCase: "Communicate effectively and promote understanding",
				slug: "/tools/connect/ladder-of-inference",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "NVC",
				category: "Establish effective and efficient communication",
				useCase: "",
				slug: "/tools/connect/nvc",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Non-Violent Communication",
				category: "Establish effective and efficient communication",
				useCase:
					"Manage emotions and difficult interactions positively",
				slug: "/tools/connect/non-violent-communication",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Difficult Conversations",
				category: "Establish effective and efficient communication",
				useCase:
					"Manage emotions and difficult interactions positively",
				slug: "/tools/connect/difficult-conversations",
				icon: "/vectors/tools/tool.png",
			},
		],
	},
	{
		id: "create",
		title: "Create a high-impact deal",
		label: "Create",
		icon: "/icons/pizza.svg",
		theme: {
			background: "#FFE4B1",
		},
		items: [
			{
				text: "Parties & Issues Scoping",
				category: "Satisfy everyone's true interests",
				useCase: "Create value and expand the pie",
				slug: "/tools/create/parties---issues-scoping",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Positions Buster",
				category: "Satisfy everyone's true interests",
				useCase: "Discover what parties truly want",
				slug: "/tools/create/positions-buster",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Role Reversal",
				category: "Satisfy everyone's true interests",
				useCase: "Discover what parties truly want",
				slug: "/tools/create/role-reversal",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Interests Frameworks",
				category: "Satisfy everyone's true interests",
				useCase: "Discover what parties truly want",
				slug: "/tools/create/interests-frameworks",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Interests Ranking",
				category: "Satisfy everyone's true interests",
				useCase: "Prioritize and negotiate many different issues",
				slug: "/tools/create/interests-ranking",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Interests Buckets",
				category: "Satisfy everyone's true interests",
				useCase: "Tailor solutions to different interests",
				slug: "/tools/create/interests-buckets",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "OptionStorming",
				category: "Maximize impact with creative options",
				useCase: "Create value and expand the pie",
				slug: "/tools/create/optionstorming",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Tailored Options",
				category: "Maximize impact with creative options",
				useCase: "Tailor solutions to different interests",
				slug: "/tools/create/tailored-options",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "The Three Negotiations",
				category: "Maximize impact with creative options",
				useCase: "Tailor solutions to different interests",
				slug: "/tools/create/the-three-negotiations",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Pareto Improvements",
				category: "Maximize impact with creative options",
				useCase: "Create value and expand the pie",
				slug: "/tools/create/pareto-improvements",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Package Negotiations",
				category: "Maximize impact with creative options",
				useCase: "Prioritize and negotiate many different issues",
				slug: "/tools/create/package-negotiations",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "No Limits",
				category: "Maximize impact with creative options",
				useCase: "Create value and expand the pie",
				slug: "/tools/create/no-limits",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Sources of Legitimacy",
				category: "Persuade with legitimacy",
				useCase: "Persuade others and claim value",
				slug: "/tools/create/sources-of-legitimacy",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Persuasive Processes",
				category: "Persuade with legitimacy",
				useCase: "Persuade others and claim value",
				slug: "/tools/create/persuasive-processes",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Cognitive Biases",
				category: "Persuade with legitimacy",
				useCase: "Address decision-making biases",
				slug: "/tools/create/cognitive-biases",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Principles of Influence",
				category: "Persuade with legitimacy",
				useCase: "Address decision-making biases",
				slug: "/tools/create/principles-of-influence",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Apples to Apples",
				category: "Persuade with legitimacy",
				useCase: "Prioritize and negotiate many different issues",
				slug: "/tools/create/apples-to-apples",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "First Offer",
				category: "Persuade with legitimacy",
				useCase: "Persuade others and claim value",
				slug: "/tools/create/first-offer",
				icon: "/vectors/tools/tool.png",
			},
		],
	},
	{
		id: "choose",
		title: "Choose the best way forward",
		label: "Choose",
		icon: "/icons/directions.svg",
		theme: {
			background: "#FBDBD9",
		},
		items: [
			{
				text: "Build our Alternatives",
				category: "Ensure a deal better than alternatives",
				useCase: "Negotiate with lower power",
				slug: "/tools/choose/build-our-alternatives",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Reduce their Alternatives",
				category: "Ensure a deal better than alternatives",
				useCase: "Negotiate with lower power",
				slug: "/tools/choose/reduce-their-alternatives",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Use our Plan B",
				category: "Ensure a deal better than alternatives",
				useCase: "Walk away from a negotiation",
				slug: "/tools/choose/use-our-plan-b",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Handle their Plan B",
				category: "Ensure a deal better than alternatives",
				useCase: "Negotiate with lower power",
				slug: "/tools/choose/handle-their-plan-b",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Do Nothing",
				category: "Ensure a deal better than alternatives",
				useCase: "Walk away from a negotiation",
				slug: "/tools/choose/do-nothing",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Burn the Ships",
				category: "Ensure a deal better than alternatives",
				useCase: "Make good decisions",
				slug: "/tools/choose/burn-the-ships",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Roadmap to Agreement",
				category: "Implement a solid commitment",
				useCase: "Structure the process and focus on what matters",
				slug: "/tools/choose/roadmap-to-agreement",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Term Sheet",
				category: "Implement a solid commitment",
				useCase: "Structure the process and focus on what matters",
				slug: "/tools/choose/term-sheet",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Crystal Ball",
				category: "Implement a solid commitment",
				useCase: "Make good decisions",
				slug: "/tools/choose/crystal-ball",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Perceived Choice",
				category: "Implement a solid commitment",
				useCase: "Help the other party say Yes",
				slug: "/tools/choose/perceived-choice",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Success Speech",
				category: "Implement a solid commitment",
				useCase: "Help the other party say Yes",
				slug: "/tools/choose/success-speech",
				icon: "/vectors/tools/tool.png",
			},
			{
				text: "Decision Models",
				category: "Implement a solid commitment",
				useCase: "Make good decisions",
				slug: "/tools/choose/decision-models",
				icon: "/vectors/tools/tool.png",
			},
		],
	},
];
